# Урок1 -  NUMPY - Задание1

In [34]:
import numpy as np

In [62]:
a = np.array([[1, 6], [2,8], [3, 11], [3, 10], [1, 7]])

In [64]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [67]:
mean_a = a.mean(axis = 0)

In [68]:
mean_a

array([2. , 8.4])

# Задание2

In [177]:
a_centered = a - mean_a

In [178]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

# Задание3

In [181]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [197]:
a_centered_sp = a_centered.transpose()[0] @ a_centered.transpose()[1] / (5 - 1)

In [198]:
a_centered_sp

2.0

# Задание4

In [203]:
np.cov(a.transpose())

array([[1. , 2. ],
       [2. , 4.3]])

# Урок1 -  PANDAS - Задание1

In [211]:
import pandas as pd

In [262]:
authors = pd.DataFrame({'author_id': ['1', '2', '3'], 'author_name': ['Тургенев', 'Чехов', 'Островский']})

In [257]:
authors


author_id author_name
0         1    Тургенев
1         2       Чехов
2         3  Островский

In [275]:
book = pd.DataFrame({'author_id': ['1', '1', '1', '2', '2', '3', '3'], 'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 'price': [450, 300, 350, 500, 450, 370, 290]})

In [276]:
book

author_id            book_title  price
0         1           Отцы и дети    450
1         1                 Рудин    300
2         1     Дворянское гнездо    350
3         2      Толстый и тонкий    500
4         2       Дама с собачкой    450
5         3                 Гроза    370
6         3  Таланты и поклонники    290

# Задание 2

In [419]:
authors_price = pd.merge(authors, book, on = 'author_id', how = 'outer')

In [279]:
authors_price

author_id author_name            book_title  price
0         1    Тургенев           Отцы и дети    450
1         1    Тургенев                 Рудин    300
2         1    Тургенев     Дворянское гнездо    350
3         2       Чехов      Толстый и тонкий    500
4         2       Чехов       Дама с собачкой    450
5         3  Островский                 Гроза    370
6         3  Островский  Таланты и поклонники    290

# Задание 3

In [296]:
top5 = authors_price.sort_values(by='price').tail(5)

In [290]:
top5

author_id author_name         book_title  price
2         1    Тургенев  Дворянское гнездо    350
5         3  Островский              Гроза    370
0         1    Тургенев        Отцы и дети    450
4         2       Чехов    Дама с собачкой    450
3         2       Чехов   Толстый и тонкий    500

# Задание 4

In [403]:
authors_stat = pd.concat([
    authors_price.groupby('author_name')['price'].min(),
    authors_price.groupby('author_name')['price'].max(),
    authors_price.groupby('author_name')['price'].mean()
    ], axis=1)
authors_stat.columns=['min','max','mean']

In [404]:
authors_stat

min  max        mean
author_name                      
Островский   290  370  330.000000
Тургенев     300  450  366.666667
Чехов        450  500  475.000000

# Задание 5

In [420]:
authors_price['cover'] = pd.Series(['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'])

In [422]:
authors_price

author_id author_name            book_title  price    cover
0         1    Тургенев           Отцы и дети    450  твердая
1         1    Тургенев                 Рудин    300   мягкая
2         1    Тургенев     Дворянское гнездо    350   мягкая
3         2       Чехов      Толстый и тонкий    500  твердая
4         2       Чехов       Дама с собачкой    450  твердая
5         3  Островский                 Гроза    370   мягкая
6         3  Островский  Таланты и поклонники    290   мягкая

In [442]:
help(pd.pivot_table)

Help on function pivot_table in module pandas.core.reshape.pivot:

pivot_table(data, values=None, index=None, columns=None, aggfunc='mean', fill_value=None, margins=False, dropna=True, margins_name='All', observed=False) -> 'DataFrame'
    Create a spreadsheet-style pivot table as a DataFrame.
    
    The levels in the pivot table will be stored in MultiIndex objects
    (hierarchical indexes) on the index and columns of the result DataFrame.
    
    Parameters
    ----------
    data : DataFrame
    values : column to aggregate, optional
    index : column, Grouper, array, or list of the previous
        If an array is passed, it must be the same length as the data. The
        list can contain any of the other types (except list).
        Keys to group by on the pivot table index.  If an array is passed,
        it is being used as the same manner as column values.
    columns : column, Grouper, array, or list of the previous
        If an array is passed, it must be the same lengt

In [444]:
book_info = pd.pivot_table(authors_price, index='author_name', columns='cover', fill_value='0')

In [445]:
book_info

price        
cover       мягкая твердая
author_name               
Островский   330.0       0
Тургенев     325.0   450.0
Чехов            0   475.0

In [447]:
book_info.to_pickle("book_info.pkl")

In [449]:
book_info2 = pd.read_pickle("book_info.pkl")

In [450]:
book_info2

price        
cover       мягкая твердая
author_name               
Островский   330.0       0
Тургенев     325.0   450.0
Чехов            0   475.0

In [462]:
book_info = book_info2